#!/bin/sh
python createdb.py
python example_project/manage.py syncdb --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/data/static
python example/manage.py collectstatic --noinput
